### ISSUE TITLE
Different limits per option of number of participants

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1712]
## Describe the goal you'd like to achieve
We use Polls to assign members to trainingsession. 
The current limit helps to not have to many at the same session but as we have different amounts of space at different dates we need multiple polls or have to change the limit on the fly to acomodate that.
Assigning different limits per option would help with that.

**Comment by dartcafe** [comment]
I understand the use case, but I don' believe this be developed. Sorry. To much work for a limited value IMHO. I put it into the backlog.

**Comment by thefeiter** [comment]
I would love to see this as well!

**Comment by dartcafe** [comment]
I think, this is solved via #738 and #1320 since polls 1.7

**Comment by tobyps** [comment]
No, not solved.

You can limit the votes per User and the votes per Option for the whole poll, but you still cant have different limits for different Options. As in our Usecase different Trainingsession or for example different meeting rooms for the same courses.

I get that it is on the backlog as it is more of an edge case but closing it, at least as solved, would be wrong.
If I'm mistaken please give us a short how to.

**Comment by dartcafe** [comment]
Oh yes. You are right, this is another request. I totally misinterpreded this.

**Comment by msimeon-gh** [comment]
I would love to have this feature es well! :)
