### ISSUE TITLE
Upgrade fails with: "InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default."

### ISSUE THREAD

**Issue by appzer0** [nextcloud/polls#1723]
Upgrade fails with log as follows:

```
InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.

    /var/www/nextcloud/lib/private/DB/MigrationService.php - line 539:

    OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)

    /var/www/nextcloud/lib/private/DB/MigrationService.php - line 426:

    OC\DB\MigrationService->executeStep("0109Date20210323120002", false)

    /var/www/nextcloud/lib/private/legacy/OC_App.php - line 993:

    OC\DB\MigrationService->migrate()

    /var/www/nextcloud/lib/private/Updater.php - line 340:

    OC_App::updateApp("*** sensiti ... *")

    /var/www/nextcloud/lib/private/Updater.php - line 260:

    OC\Updater->doAppUpgrade()

    /var/www/nextcloud/lib/private/Updater.php - line 132:

    OC\Updater->doUpgrade("21.0.2.1", "21.0.2.1")

    /var/www/nextcloud/core/Command/Upgrade.php - line 255:

    OC\Updater->upgrade()

    /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php - line 255:

    OC\Core\Command\Upgrade->execute(Symfony\Comp ... {}, Symfony\Comp ... {})

    /var/www/nextcloud/3rdparty/symfony/console/Application.php - line 1009:

    Symfony\Component\Console\Command\Command->run(Symfony\Comp ... {}, Symfony\Comp ... {})

    /var/www/nextcloud/3rdparty/symfony/console/Application.php - line 273:

    Symfony\Component\Console\Application->doRunCommand(OC\Core\Comm ... }}, Symfony\Comp ... {}, Symfony\Comp ... {})

    /var/www/nextcloud/3rdparty/symfony/console/Application.php - line 149:

    Symfony\Component\Console\Application->doRun(Symfony\Comp ... {}, Symfony\Comp ... {})

    /var/www/nextcloud/lib/private/Console/Application.php - line 215:

    Symfony\Component\Console\Application->run(Symfony\Comp ... {}, Symfony\Comp ... {})

    /var/www/nextcloud/console.php - line 100:

    OC\Console\Application->run()

    /var/www/nextcloud/occ - line 11:

    require_once("/var/www/ne ... p")
```

**Comment by Niemand112233** [comment]
Same here

**Comment by jonbulica99** [comment]
bump, any follow up on this?

**Comment by ei8fdb** [comment]
Here's my report:

**Steps to replicate**
- as admin go to apps
- update polls app

**Result**
Printout on nextcloud instance web interface:
```
InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Delete duplicates
InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.
```

Work-around:
go to commandline

```
occ app:disable polls
occ app:update polls # try to update, no output on commandline
```

Go to web interface, navigate to apps, try to update polls app, get this result:

![image](https://user-images.githubusercontent.com/1899506/121672848-92bf5680-cab0-11eb-9cb0-7f0694fbdbd6.png)

**Outcome**
Polls app is disabled but Nextcloud instance is running.

**Comment by ei8fdb** [comment]
> bump, any follow up on this?
> Edit: possibly related to #1701

This message suggests *manually* updating to 1.9.5 using the referenced zip file.

https://github.com/nextcloud/polls/issues/1701#issuecomment-856624623

I can confirm following the steps in this message gets polls (version 1.9.5) working. 

You will then be prompted to update to version 2.0.0. This still does not work.

**Comment by jonbulica99** [comment]
I managed to solve the issue by doing what @ei8fdb mentioned and then additionally running the following SQL statement:
```sql
ALTER TABLE oc_polls_options ADD owner VARCHAR(64) NOT NULL DEFAULT 'admin';
```
I recreated this from here https://github.com/nextcloud/polls/blob/c3b16b11a592d4eeb2d3d8766421270bd28e3f70/lib/Migration/Version0109Date20210323120002.php#L78-L82
After that, you can safely update/enable the app again and it will work.

**Comment by ei8fdb** [comment]
> then additionally running the following SQL statement:

You're braver than I. I stay away from databases as much as possible! 👻 😨

**Comment by tilllt** [comment]
same same

> docker exec -it --user www-data nc_container /var/www/html/occ upgrade
> Nextcloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Setting log level to debug
> Turned on maintenance mode
> Updating database schema
> Updated database
> Updating <polls> ...
> InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.
> Update failed
> Maintenance mode is kept active
> Resetting log level

**Comment by ei8fdb** [comment]
> same same

Solution here: https://github.com/nextcloud/polls/issues/1723#issuecomment-859488474

**Comment by tilllt** [comment]
> > same same
> 
> Solution here: [#1723 (comment)](https://github.com/nextcloud/polls/issues/1723#issuecomment-859488474)

Thanks for the pointer. My solution for now is:
occ app:disable polls

until they release a fix.

**Comment by ei8fdb** [comment]
> until they release a fix.

https://github.com/nextcloud/polls/issues/1725#issuecomment-859516325

**Comment by ei8fdb** [comment]
The correct fix is https://github.com/nextcloud/polls/issues/1732

**Comment by dartcafe** [comment]
fixed with appstore release.

**Comment by tilllt** [comment]
Works again, thanks a lot.

**Comment by FlederFau** [comment]
Hello,
it seems to me that I have the same issue but the update didn't fix it.
I am using Nextcloud 27.1.15 and Polls 5.4.2 but when trying to enable it I get the error:
```
Database error when running migration 050100Date20230515083001 for app polls
Column "oc_polls_options"."owner" is NotNull, but has empty string or null as default.
```
I already reinstalled it but nothing changed. Some help would be highly appreciated!
