### ISSUE TITLE
Multiple Error Messages in NC Log - orphaned data of deleted polls?

### ISSUE THREAD

**Issue by ChrWieg** [nextcloud/polls#3926]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Adding, viewing oder editing a poll causes multiple error entries at nextcloud log.
The logs refer to rather old and archived / deleted polls
Neither of theses commands nor reinstalling polls fixed the Problem: occ polls:db:purge, occ polls:db:rebuild, occ polls:index:create, occ polls:index:remove, occ polls:db:clean-migrations

### What did you expect, how polls should behave instead?

Polls should remove old polls completely, when the user archives and delete them. No error should be appear in the log.

### What steps does it need to replay this bug?

Add, open or edit a poll.

### Installation method

Installed/updated using occ

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.4.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [x] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

Brave

### Add your browser log here

```json
No Output in the browser console
```

### NC version

Nextcloud 31

### Other Nextcloud version

31.0.2.1

### PHP engine version

PHP 8.3

### Other PHP version

8.3.19

### Database engine

MySQL

### Database Engine version or other Database

PostgreSQL 13.20

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other/Don't know

### Add your nextcloud server log here

```shell
{
    "reqId": "k4FAyf5sBDMfy4KcQwVs",
    "level": 3,
    "time": "2025-03-22T09:39:03+00:00",
    "remoteAddr": "80.81.24.58",
    "user": "CW",
    "app": "activity",
    "method": "GET",
    "url": "/ocs/v2.php/apps/activity/api/v2/activity/polls?format=json&since=0&limit=50&object_type=poll&object_id=1",
    "message": "Object for placeholder pollTitle is invalid, value 4 for key id is not a string",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "version": "31.0.2.1",
    "exception": {
        "Exception": "OCP\\RichObjectStrings\\InvalidObjectExeption",
        "Message": "Object for placeholder pollTitle is invalid, value 4 for key id is not a string",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/html/lib/private/RichObjectStrings/Validator.php",
                "line": 59,
                "function": "validateParameter",
                "class": "OC\\RichObjectStrings\\Validator",
                "type": "->",
                "args": [
                    "pollTitle",
                    {
                        "type": "highlight",
                        "id": 4,
                        "name": "OT Bands & Technik",
                        "link": "https://cloud.leviocloud.de/apps/polls/vote/4"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/GroupHelper.php",
                "line": 75,
                "function": "validate",
                "class": "OC\\RichObjectStrings\\Validator",
                "type": "->",
                "args": [
                    "{sharee} hat sich f\u00fcr die Umfrage {pollTitle} registriert",
                    {
                        "pollTitle": {
                            "type": "highlight",
                            "id": 4,
                            "name": "OT Bands & Technik",
                            "link": "https://cloud.leviocloud.de/apps/polls/vote/4"
                        },
                        "shareType": {
                            "type": "highlight",
                            "id": 23,
                            "name": "external"
                        },
                        "sharee": {
                            "type": "guest",
                            "id": "ex_yiLVVoqz",
                            "name": "Leo"
                        },
                        "actor": {
                            "type": "guest",
                            "id": "JW7ksadl",
                            "name": "Deleted User"
                        }
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/GroupHelper.php",
                "line": 47,
                "function": "addEvent",
                "class": "OCA\\Activity\\GroupHelper",
                "type": "->",
                "args": [
                    128967,
                    {
                        "__class__": "OC\\Activity\\Event"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Data.php",
                "line": 232,
                "function": "addActivity",
                "class": "OCA\\Activity\\GroupHelper",
                "type": "->",
                "args": [
                    {
                        "activity_id": 128967,
                        "timestamp": 1742633460,
                        "priority": 30,
                        "type": "share_registration",
                        "user": "JW7ksadl",
                        "0": "And 10 more entries, set log level to debug to see all entries"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Controller/APIv2Controller.php",
                "line": 190,
                "function": "get",
                "class": "OCA\\Activity\\Data",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\GroupHelper"
                    },
                    {
                        "__class__": "OCA\\Activity\\UserSettings"
                    },
                    "CW",
                    0,
                    46,
                    "desc",
                    "polls",
                    "poll",
                    1
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Controller/APIv2Controller.php",
                "line": 137,
                "function": "get",
                "class": "OCA\\Activity\\Controller\\APIv2Controller",
                "type": "->",
                "args": [
                    "polls",
                    0,
                    50,
                    false,
                    "poll",
                    1,
                    "desc"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 200,
                "function": "getFilter",
                "class": "OCA\\Activity\\Controller\\APIv2Controller",
                "type": "->",
                "args": [
                    "polls",
                    0,
                    50,
                    false,
                    "poll",
                    1,
                    "desc"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 114,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\Controller\\APIv2Controller"
                    },
                    "getFilter"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/App.php",
                "line": 161,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\Controller\\APIv2Controller"
                    },
                    "getFilter"
                ]
            },
            {
                "file": "/var/www/html/lib/private/Route/Router.php",
                "line": 307,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Activity\\Controller\\APIv2Controller",
                    "getFilter",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "filter": "polls",
                        "_route": "ocs.activity.apiv2.getfilter"
                    }
                ]
            },
            {
                "file": "/var/www/html/ocs/v1.php",
                "line": 49,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/ocsapp/apps/activity/api/v2/activity/polls"
                ]
            },
            {
                "file": "/var/www/html/ocs/v2.php",
                "line": 7,
                "args": [
                    "/var/www/html/ocs/v1.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/var/www/html/lib/private/RichObjectStrings/Validator.php",
        "Line": 85,
        "message": "Object for placeholder pollTitle is invalid, value 4 for key id is not a string",
        "exception": {},
        "CustomMessage": "Object for placeholder pollTitle is invalid, value 4 for key id is not a string"
    }
}
```

### Additional environment informations

NC running with docker image 31.0.2-fpm (https://github.com/nextcloud/docker/blob/e56b9a4e2e400b72018d06aa94236e2a5be3e99a/31/fpm/Dockerfile)
No other errors or warning in the log file!

### Configuration report

```shell
{
    "system": {
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cloud.leviocloud.de",
        "overwriteprotocol": "https",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.leviocloud.de",
            "next-cloud_web_1",
            "web",
            "stun.nextcloud.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "31.0.2.1",
        "overwrite.cli.url": "https:\/\/cloud.leviocloud.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "updater.release.channel": "stable",
        "default_phone_region": "DE",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "allow_local_remote_servers": true,
        "enable_previews": false,
        "onlyoffice": {
            "DocumentServerUrl": "\/ds-vpath\/",
            "DocumentServerInternalUrl": "http:\/\/onlyoffice-document-server\/",
            "StorageUrl": "http:\/\/next-cloud_web_1\/",
            "verify_peer_off": true
        },
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 1800,
        "session_keepalive": false,
        "auto_logout": true,
        "maintenance_window_start": 1,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/www\/html\/data\/nextcloud.log",
        "files.chunked_upload.max_size": 20971520,
        "app_install_overwrite": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - app_api: 5.0.2
  - appointments: 2.4.1
  - bookmarks: 15.1.0
  - bruteforcesettings: 4.0.0
  - calendar: 5.2.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contacts: 7.0.4
  - dashboard: 7.11.0
  - dav: 1.33.0
  - deck: 1.15.0
  - federatedfilesharing: 1.21.0
  - files: 2.3.1
  - files_3dmodelviewer: 0.0.15
  - files_downloadlimit: 4.0.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - flow_notifications: 2.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - phonetrack: 0.8.2
  - photos: 4.0.0-dev.1
  - polls: 7.4.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - quota_warning: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - richdocuments: 8.6.3
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - spreed: 21.0.1
  - systemtags: 1.21.1
  - tables: 0.9.0
  - tasks: 0.16.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - twofactor_totp: 13.0.0-dev.0
  - updatenotification: 1.21.0
  - user_ldap: 1.22.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - whiteboard: 1.0.5
  - workflowengine: 2.13.0
Disabled:
  - circles: 31.0.0 (installed 29.0.0-dev)
  - contactsinteraction: 1.12.0 (installed 1.12.0)
  - encryption: 2.19.0 (installed 2.17.0)
  - federation: 1.21.0 (installed 1.21.0)
  - files_external: 1.23.0 (installed 1.23.0)
  - support: 3.0.0 (installed 3.0.0)
  - survey_client: 3.0.0 (installed 3.0.0)
  - suspicious_login: 9.0.1
  - twofactor_nextcloud_notification: 5.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by dartcafe** [comment]
This seems to come from Activity items of the Activities app, which reference to non existent polls. You should find them inside the table `oc_activities`. 

I would expect, that the Activity app would discard these entries, rather than logging them.

@nickvergessen Is there anything I missed in the polls app?

**Comment by ChrWieg** [comment]
Das Problem besteht auch bei aktuellen (also nicht gelöschten oder archivierten Polls.

Und die geloggten Aktivitäten sehen ungesund aus (malformed):

![Image](https://github.com/user-attachments/assets/d61aaf7a-eab0-4c6a-a835-20a7706014fe)

`{
    "reqId": "wpq89f1QdTFFUexd5rLW",
    "level": 3,
    "time": "2025-03-23T08:13:10+00:00",
    "remoteAddr": "80.81.24.58",
    "user": "CW",
    "app": "activity",
    "method": "GET",
    "url": "/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0",
    "message": "Object for placeholder pollTitle is invalid, value 1 for key id is not a string",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "version": "31.0.2.1",
    "exception": {
        "Exception": "OCP\\RichObjectStrings\\InvalidObjectExeption",
        "Message": "Object for placeholder pollTitle is invalid, value 1 for key id is not a string",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/html/lib/private/RichObjectStrings/Validator.php",
                "line": 59,
                "function": "validateParameter",
                "class": "OC\\RichObjectStrings\\Validator",
                "type": "->",
                "args": [
                    "pollTitle",
                    {
                        "type": "highlight",
                        "id": 1,
                        "name": "Test",
                        "link": "https://cloud.leviocloud.de/apps/polls/vote/1"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/GroupHelper.php",
                "line": 75,
                "function": "validate",
                "class": "OC\\RichObjectStrings\\Validator",
                "type": "->",
                "args": [
                    "Du hast in der Umfrage {pollTitle} abgestimmt",
                    {
                        "pollTitle": {
                            "type": "highlight",
                            "id": 1,
                            "name": "Test",
                            "link": "https://cloud.leviocloud.de/apps/polls/vote/1"
                        },
                        "actor": {
                            "type": "user",
                            "id": "CW",
                            "name": "ChrWieg"
                        }
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/GroupHelper.php",
                "line": 47,
                "function": "addEvent",
                "class": "OCA\\Activity\\GroupHelper",
                "type": "->",
                "args": [
                    128983,
                    {
                        "__class__": "OC\\Activity\\Event"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Data.php",
                "line": 232,
                "function": "addActivity",
                "class": "OCA\\Activity\\GroupHelper",
                "type": "->",
                "args": [
                    {
                        "0": "And 10 more entries, set log level to debug to see all entries",
                        "activity_id": 128983,
                        "timestamp": 1742714494,
                        "priority": 30,
                        "type": "vote_set",
                        "user": "CW"
                    }
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Controller/APIv2Controller.php",
                "line": 190,
                "function": "get",
                "class": "OCA\\Activity\\Data",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\GroupHelper"
                    },
                    {
                        "__class__": "OCA\\Activity\\UserSettings"
                    },
                    "CW",
                    0,
                    49,
                    "desc",
                    "all",
                    "",
                    0
                ]
            },
            {
                "file": "/var/www/html/apps/activity/lib/Controller/APIv2Controller.php",
                "line": 137,
                "function": "get",
                "class": "OCA\\Activity\\Controller\\APIv2Controller",
                "type": "->",
                "args": [
                    "all",
                    0,
                    50,
                    true,
                    "",
                    0,
                    "desc"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 200,
                "function": "getFilter",
                "class": "OCA\\Activity\\Controller\\APIv2Controller",
                "type": "->",
                "args": [
                    "all",
                    0,
                    50,
                    true,
                    "",
                    0,
                    "desc"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 114,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\Controller\\APIv2Controller"
                    },
                    "getFilter"
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/App.php",
                "line": 161,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Activity\\Controller\\APIv2Controller"
                    },
                    "getFilter"
                ]
            },
            {
                "file": "/var/www/html/lib/private/Route/Router.php",
                "line": 307,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Activity\\Controller\\APIv2Controller",
                    "getFilter",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "filter": "all",
                        "_route": "ocs.activity.apiv2.getfilter"
                    }
                ]
            },
            {
                "file": "/var/www/html/ocs/v1.php",
                "line": 49,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/ocsapp/apps/activity/api/v2/activity/all"
                ]
            },
            {
                "file": "/var/www/html/ocs/v2.php",
                "line": 7,
                "args": [
                    "/var/www/html/ocs/v1.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/var/www/html/lib/private/RichObjectStrings/Validator.php",
        "Line": 85,
        "message": "Object for placeholder pollTitle is invalid, value 1 for key id is not a string",
        "exception": [],
        "CustomMessage": "Object for placeholder pollTitle is invalid, value 1 for key id is not a string"
    },
    "id": "67dfc2d56ee69"
}`

**Comment by nickvergessen** [comment]
On the phone I can't find the code, but the id you set on the rich object of the message or subject is an integer instead of a string. Just cast it to `(string)`

**Comment by dartcafe** [comment]
Ah yes. That should be #3889 and already resolved by #3908. Was there a change in the activity app? Integer seemed not to an issue before.

But I have no chance to fix prior created activity items, without manipulating a foreign table (which polls will never do).

**Comment by dartcafe** [comment]
@ChrWieg I was wrong. I did not read the initial error message. The problem comes from a wrong object type.

Anyways. This is a resolved bug but unfortunately old entries will still have that issue.

**Comment by ChrWieg** [comment]
> [@ChrWieg](https://github.com/ChrWieg) I was wrong. I did not read the initial error message. The problem comes from a wrong object type.
> 
> Anyways. This is a resolved bug but unfortunately old entries will still have that issue.

Do you mean "old entries" of the acitvity log? As I mentioned above, I deleted all the activity log entries, but the error came back with new polls. Fixed with which version?

By the way, polls is a very cool and useful plugin. Thanks a lot for this tool!
