### ISSUE TITLE
Polls upgrade issue: Not null violation

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/polls#4213]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

```
$ ./occ app:enable polls
Database error when running migration 080300Date20250812231603 for app polls
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "group_id" of relation "oc_polls_share" contains null values
```

After upgrading to latest master on daily LTD: 8.3.0-beta.1

### What did you expect, how polls should behave instead?

no error during update

### What steps does it need to replay this bug?

checkout master
update

### Affected polls version

master

### Installation method

Installed/updated using occ

### Installation type

Updated from a minor version within same major version (i.e. 8.0.0 to 8.1.2)

### Can you rule out that any extension you use is involved in the issue?

- [ ] I have checked all browser extension

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Add your browser log here

```json

```

### NC version

Nextcloud 27

### PHP engine version

PHP 8.1

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```json

```

### Configuration report

```shell

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

**Comment by dartcafe** [comment]
Please check https://github.com/nextcloud/polls/wiki/Installation-help#update-issues

**Comment by solracsf** [comment]
```
# occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Updating <polls> ...
Exception: Database error when running migration 080300Date20250812231603 for app polls
An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'group_id' at row 1
Update failed
Maintenance mode is kept active
Resetting log level
```
Followed by:

```
# occ app:disable polls
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
polls 8.3.0-beta.1 disabled

# occ maintenance:mode --off
Maintenance mode disabled

# occ app:enable polls
Database error when running migration 080300Date20250812231603 for app polls
An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'group_id' at row 1
```
Polls can't be re-enabled.

NC 30.0.14
Polls 8.3.0-beta.1

**Comment by dartcafe** [comment]
Polls 8.3.0-beta.2 should fix that by validating and fixing the records. 
Will come out this weekend, after some final tests and some minor fixes and tidy.

**Comment by tobiasKaminsky** [comment]
Thanks for fixing it.
However on my latest master it still does not work:
I am testing with 9f17ddc24386db195fbc955a06e4d92143e6a4b0
and then
```
1a60486d2be6:/var/www/html$ ./occ app:enable polls
Database error when running migration 080300Date20250816201201 for app polls
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "group_id" of relation "oc_polls_share" contains null values
```

We run a daily "server" that updates twice each day and runs entirely on latest master.
Can it be that some intermetiade step kills the upgrade?
I am happy to manually fiddle around in DB, if needed.

**Comment by dartcafe** [comment]
Strange. I tested it with forbidden db states; The migration fixed it. 

What does `occ upgrade` say? 

Manual fix of oc_polls_shares (that is what the migration does): 
* remove all unique indices 
* remove all fk constraints 
* replace all null values in the columns group_id and polls_id with 0

Enable polls.

**Comment by tobiasKaminsky** [comment]
> What does `occ upgrade` say?

The same error.

I fear I will have to go with manual way :)

**Comment by dartcafe** [comment]
Could you provide the content of oc_polls_shares

**Comment by tobiasKaminsky** [comment]
```
nextcloud_database=> select * from oc_polls_share;
 id | poll_id |  token   |   type   |                label                 |         user_id          |        display_name         |              email_address               | invitation_sent | reminder_sent | locked |          misc_settings          | deleted | group_id 
----+---------+----------+----------+--------------------------------------+--------------------------+-----------------------------+------------------------------------------+-----------------+---------------+--------+---------------------------------+---------+----------
  1 |       1 | NHD      | email    |                                      | info                     | Name                        | email                                    |      1726734854 |             0 |      0 |                                 |       0 |        0
  2 |       6 | fiV      | public   |                                      | fiVJZNzv                 |                             |                                          |      1727682420 |             0 |      0 |                                 |       0 |        0
 12 |       8 | Sb5      | public   |                                      | Sb5fSVXU                 |                             |                                          |      1732010465 |             0 |      0 |                                 |       0 |        0
 13 |      11 | 3z3      | public   |                                      | 3z3loH8G                 |                             |                                          |      1739601995 |    1740895401 |      0 |                                 |       0 |        0
 14 |      12 | pfS      | external |                                      | ex_Kr60hEwz              | Name                        | email                                    |               0 |             0 |      0 | {"timeZone":"","language":""}   |       0 |        0
  3 |       7 | Rvp      | public   |                                      | RvpBwAlX                 |                             |                                          |      1731585894 |    1752247040 |      0 | {"publicPollEmail":"mandatory"} |       0 |        0
  4 |       7 | Vb3      | external |                                      | ex_4YJ8LVdK              | Name                        | email                                    |      1731592392 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
  5 |       7 | zK5      | external |                                      | ex_JH3S0zY1              | Name                        | email                                    |      1731592606 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
  6 |       7 | 57n      | external |                                      | ex_9ERLOrZK              | Name                        | email                                    |      1731596152 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
  7 |       7 | 6zT      | external |                                      | ex_758sK6HV              | Name                        | email                                    |      1731621891 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
  8 |       7 | nVV      | external |                                      | ex_sNLnXE1y              | Name                        | email                                    |      1731656162 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
  9 |       7 | pEf      | external |                                      | ex_5VlKa9H6              | Name                        | email                                    |      1731658942 |    1752247041 |      0 | {"language":"fr","timeZone":""} |       0 |        0
 10 |       7 | eRx      | external |                                      | ex_IwRBlVh5              | Name                        | email                                    |      1731659429 |    1752247042 |      0 | {"language":"fr","timeZone":""} |       0 |        0
 11 |       7 | b5r      | external |                                      | ex_tN2oNtZS              | Name                        | email                                    |      1731661769 |    1752247042 |      0 | {"language":"fr","timeZone":""} |       0 |        0
(14 rows)

```

I truncated thge tokens a bit and replaced user_id and display_name, but this should not matter 🤞

**Comment by Klaupe** [comment]
The error still occurs when trying to upgrade from 7.X to 8.3.0

We had the same issue and found the following workaround. 

1. `occ app:remove polls`
2. Download the Version 8.2.2
3. `occ app:enable polls`
4. `occ app:update polls`
5. `occ polls:db:rebuild`

Please make sure to fix this issue, when upgrading from versions 7.X

**Comment by dartcafe** [comment]
I do not understand it: 
> "group_id" of relation "oc_polls_share" contains null values

* I see no null values in your db snapshot (and no the truncation does not matter). 
* I tested a couple of complicated combinations to test the migration. In all cases (poll_id and group_id):
  * FK constraints got removed,
  * unique indices got removed,
  * generic indices got removed,
  * null values got replaced with 0 and
  * notnull got changed from false to true.

I always finished with a working instance. 

Are there any additional FK constraints or indices, maybe from a intermediate test version?

**Comment by dartcafe** [comment]
> Please make sure to fix this issue, when upgrading from versions 7.X

Have to check from a version 7.x. But also strange...

**Comment by tobiasKaminsky** [comment]
> Are there any additional FK constraints or indices, maybe from a intermediate test version?

```
nextcloud_database-> \d oc_polls_share
                                        Table "public.oc_polls_share"
     Column      |          Type          | Collation | Nullable |                  Default                   
-----------------+------------------------+-----------+----------+--------------------------------------------
 id              | bigint                 |           | not null | nextval('oc_polls_share_id_seq'::regclass)
 poll_id         | bigint                 |           | not null | 0
 token           | character varying(64)  |           | not null | ''::character varying
 type            | character varying(64)  |           | not null | ''::character varying
 label           | character varying(256) |           |          | ''::character varying
 user_id         | character varying(256) |           | not null | ''::character varying
 display_name    | character varying(256) |           |          | NULL::character varying
 email_address   | character varying(256) |           |          | NULL::character varying
 invitation_sent | bigint                 |           | not null | 0
 reminder_sent   | bigint                 |           | not null | 0
 locked          | bigint                 |           | not null | 0
 misc_settings   | text                   |           |          | 
 deleted         | bigint                 |           | not null | 0
 group_id        | bigint                 |           | not null | 0
Indexes:
    "oc_polls_share_pkey" PRIMARY KEY, btree (id)
    "idx_1c85e16c3c947c0f" btree (poll_id)
    "uniq_shares" UNIQUE, btree (poll_id, user_id)
```

I hope this helps you.
If you need more, please tell me :)

**Comment by dartcafe** [comment]
And where the hell does the system see null values?

**Comment by dartcafe** [comment]
> The error still occurs when trying to upgrade from 7.X to 8.3.0

I assume the same cause as in #4224

**Comment by rakekniven** [comment]
Have the same issue on NC v31.0.8 and polls v8.2.2

`Updating <polls> ...
Exception: Database error when running migration 080301Date20250822182903 for app polls
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "group_id" of relation "oc_polls_share" contains null values`

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/releases/tag/v8.3.3-alpha.2 should fix it, too.

**Comment by tobiasKaminsky** [comment]
@dartcafe since I use master, it unfortunately still happens.
I am still unsure if this is a real problem on this app, or a more general problem with postgresql/nc.

**Comment by tobiasKaminsky** [comment]
I now did a backup of oc_polls_share.
Deleted everything from it.

But error remains the same.

**Comment by tobiasKaminsky** [comment]
Removing the table via "drop table" and let polls recreate it via "occ app:enable polls" leads to a new created table, but the same error.

**Comment by dartcafe** [comment]
`080301Date20250822182903` was removed from the current version.
* disable Polls
* empty the app/polls folder
* drop in the files from the current release
* enable Polls

**Comment by tobiasKaminsky** [comment]
So, in our daily instance we also had DB sharding enabled.
It turned out that this is the problem.

On DB1 the migration failed, but worked on DB"0".

We then need to figure out, why this is even a problem/ why migration is applied on db1/shard1.

**Comment by tobiasKaminsky** [comment]
Thanks @dartcafe for helping!

Still it is strange that @rakekniven also ran into that problem.

**Comment by dartcafe** [comment]
I wonder how how you pull the master and apply the changes. 

Mentioning the migration `080300Date20250812231603` and `080300Date20250816201201` tells me that is seems, that the app/polls folder got not emptied before the pull. Just a guess, but the only explanation, which makes sense to me atm.
