### ISSUE TITLE
1.0b2: white page and JS err in console

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#714]
I cloned the latest version from git repo master, polls updated db next login and now I get a blank page (tested different browsers and OS) and some err in the web console (eg FF):

![Bildschirmfoto 2020-01-07 um 11 05 37](https://user-images.githubusercontent.com/43957716/71887737-fd8f9400-313e-11ea-8820-245f04e9f567.png)

Previous app version was 0.10.4 running NC 17.0.2 with MariaDB 10.1.43, PHP  7.3.13 under Ubuntu 18.04.3 LTS.

**Comment by herrmannsdorfer** [comment]
Probably my fault: After cloning I did not chown the app folder (root --> www-data in my case). I assume the necessary db conversions failed because of missing permissions. No warning was shown on the front end but a lot of errors in the log:

![Bildschirmfoto 2020-01-07 um 11 28 02](https://user-images.githubusercontent.com/43957716/71888603-cde18b80-3140-11ea-8a5b-bbc21d8845f6.png)

Any chance I can rerun the process?

**Comment by herrmannsdorfer** [comment]
Now I am lost.

I rolled back my NC to a state before cloning the polls app from git repo.

Cloned again, chowned the app folder and logged on. Conversions run "without error". Polls page still empty and a few err in the log - last attempt had thrown a lot more errors but they were permissions related (forgot chown apps folder before running migration process).

![Bildschirmfoto 2020-01-07 um 12 28 10](https://user-images.githubusercontent.com/43957716/71892934-8c55de00-314a-11ea-8669-79800b289e3f.png)

![Bildschirmfoto 2020-01-07 um 12 29 19](https://user-images.githubusercontent.com/43957716/71892937-9081fb80-314a-11ea-86ed-56b0ed386042.png)

**Comment by dartcafe** [comment]
chow is not needed. There was an error in the migration. I fixed it in #713. You can replace Version0010Date20191227063812.php with the file from the PR. See #712 also.

**Comment by herrmannsdorfer** [comment]
New attempt with 1.0b2 and the mentioned PHP file from the PR: I still get a blank page. No more errors in the log - migration seems successful now. Browser cache was refreshed. Tried with several browsers and systems. FF console as an example:

![Bildschirmfoto 2020-01-08 um 12 13 03](https://user-images.githubusercontent.com/43957716/71974151-0b154e80-3211-11ea-8be5-2850fb1795e6.png)

**Comment by herrmannsdorfer** [comment]
Forget it. I messed the apps folder with different versions. 1.0b2 is running fine now. No migration issues with the Version0010Date20191227063812.php from #713 

Will test now ...
